Repository RCCTechzClub/TechzRevamp, pull requests merged in 2024-10, with the labels that each got.

#8 #Add greetings.yml
  .github/workflows/greetings.yml
Labels: level1, gssoc24-ext

#17 builded magazing page
  src/app/assest/footerbg.png
  src/app/assest/instagram.svg
  src/app/assest/linkedin.svg
  src/app/assest/logo.svg
  src/app/assest/magazing.svg
  src/app/assest/xing.svg
  src/app/assest/youtube.svg
  src/app/components/Footer.tsx
  src/app/components/TechzMagzine.tsx
  src/app/page.tsx
Labels: good first issue, hacktoberfest-accepted, level2, gssoc-ext

#19 Design "const ourWork = () => { }" Section
  src/app/globals.css
  src/app/page.tsx
  src/components/OurWork.tsx
  src/components/images/ourWork1.png
  src/components/images/ourWork2.png
  src/components/images/ourWork3.png
  src/components/images/outWork1-hi.png
  tailwind.config.ts
Labels: good first issue, level1, hacktoberfest-accepted, gssoc-ext

#25 Faq Added
  package-lock.json
  package.json
  src/app/components/Faq.tsx
  src/app/page.tsx
  src/app/utils/cn.tsx
  tailwind.config.ts
Labels: enhancement, level2, gssoc-ext

#28 Project page added
  package-lock.json
  package.json
  src/app/assest/rcctech.png
  src/app/assest/rctechlogo.png
  src/app/assest/skills/cpp.png
  src/app/assest/skills/express.png
  src/app/assest/skills/figma.png
  src/app/assest/skills/github.png
  src/app/assest/skills/java.png
  src/app/assest/skills/javascript.png
  src/app/assest/skills/mongodb.png
  src/app/assest/skills/node-js.png
  src/app/assest/skills/postman.png
  src/app/assest/skills/react.png
  src/app/assest/skills/tailwind.png
  src/app/assest/skills/vercel.jpg
  src/app/page.tsx
  src/app/projects/page.tsx
  src/components/Club.tsx
  src/components/Faq.tsx
  src/components/Footer.tsx
  src/components/ProjectItems.tsx
  src/components/SkillComponent.tsx
  src/components/TechzMagzine.tsx
  tailwind.config.ts
Labels: enhancement, level2, gssoc-ext

#39 Updated README.md
  README.md
Labels: good first issue, level1, gssoc-ext

#42 configured Error 404 page Dark theme and light theme fixed Navbar fixed homepage and title
  package-lock.json
  package.json
  src/app/components/Navbar.tsx
  src/app/components/button-mode.tsx
  src/app/components/theme-provider.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/projects/page.tsx
  src/components/Club.tsx
  src/components/Faq.tsx
  src/components/Footer.tsx
  src/components/OurWork.tsx
  src/components/ProjectItems.tsx
  src/components/SkillComponent.tsx
  src/components/TechzMagzine.tsx
  src/styles.css
  tailwind.config.ts
  tsconfig.json
Labels: bug, enhancement, level2, gssoc-ext
